tap 'caskroom/cask'

brew 'git'
brew 'yarn'
brew 'thefuck'
brew 'composer'
brew 'gradle'

# General
cask 'dropbox'
cask 'spotify'

# Developer
cask 'iterm2'
cask 'vagrant'
cask 'docker'
cask 'docker-toolbox'
cask 'gitify'
cask 'ngrok'
cask 'slack'
cask 'sequel-pro'
