tap 'caskroom/cask'

# General
cask 'dropbox'
cask 'spotify'

# Developer
brew 'git'
brew 'thefuck'
brew 'yarn'
brew 'composer'
brew 'gradle'
brew 'nvm'
cask 'iterm2'
cask 'vagrant'
cask 'docker'
cask 'docker-toolbox'
cask 'gitify'
cask 'ngrok'
cask 'slack'
cask 'sequel-pro'
